### ISSUE TITLE
Global Distribution Error

### ISSUE THREAD

**Issue by saefulbarkah** [AzenKain/KainSR#1]
![Screenshot (8)](https://github.com/user-attachments/assets/a2b0d7b8-7c94-4965-ac65-7d41ad892bc5)

**Comment by LoveFurina** [comment]
maybe server isnt fully started yet

**Comment by AzenKain** [comment]
you need to wait for the server started fully like this
![image](https://github.com/user-attachments/assets/b729d475-bed3-4a25-b298-37417d7b6116)
